package uz.nixchat.common.model.message;

import java.time.Instant;

/**
 * A service notice generated by Nchat itself: "alice joined the group", "Connection lost", etc.
 * It has no human sender.
 */
public class SystemMessage extends Message {

    private final String notice;

    public SystemMessage(String id, String chatId, Instant sentAt, String notice) {
        super(id, chatId, null, sentAt);
        this.notice = (notice == null) ? "" : notice;
    }

    public SystemMessage(String chatId, String notice) {
        this(null, chatId, null, notice);
    }

    public String getNotice() {
        return notice;
    }

    @Override
    public String preview() {
        return "ℹ " + notice;
    }

    @Override
    public String format() {
        return "— " + notice + " (" + formattedTime() + ") —";
    }

    @Override
    public String getType() {
        return "SYSTEM";
    }
}
